### ISSUE TITLE
Tensors need to be contiguous for consistent results

### ISSUE THREAD

**Issue by krrish94** [aliutkus/torchsearchsorted#11]
Hi, thanks for the great tool! I've been using this package in my work, and I've noticed that the tensors often need to be `contiguous` for results to be consistent (benchmarked wrt `tf.searchsorted()` and multiple independent calls to `torchsearchsorted.searchsorted()`).

It'll be great if you could add a word of caution to the `README` and adopt this style in the examples.

TL;DR. Use `a.contiguous()` and `v.contiguous()` before making a call to `searchsorted()`.

**Comment by aliutkus** [comment]
thanks for this. I updated the README just now

**Comment by krrish94** [comment]
FYI, this is usually needed only when you modify the underlying storage (eg. by calling `view`, `reshape` etc) after creating the tensors. It might have not cropped up in your benchmark/tests cause you typically initialize tensors, and almost immediately use them in `searchsorted`.

More of a practical issue this.

**Comment by aliutkus** [comment]
ok, that makes sense, since we are directly accessing the data in a C-manner in the c++ code

Maybe there's a smarter way to do it ?

**Comment by krrish94** [comment]
There's ways to do it, but they seem to hamper performance (see [this](https://discuss.pytorch.org/t/cuda-extension-for-non-contiguous-tensor/24878) discussion).

So, it seems like the best way ahead is to tell people to be extra-cautious when using on a tensor that could've been manipulated by ops like `view()`, `narrow()`, `permute()`, `transpose()`, etc. that break _contiguity_. This happens more frequently that you'd imagine; most neural nets have `view()` operations baked somewhere within.

**Comment by aliutkus** [comment]
yeah, ok, that's what I thought
feel free to do some PR if you feel the doc could be better and/or more explicit

thanks again for the feedback

**Comment by krrish94** [comment]
Sure, I'll take a go at it.

Very cool impl, btw!
