### ISSUE TITLE
PyPI package

### ISSUE THREAD

**Issue by krrish94** [aliutkus/torchsearchsorted#13]
Hi,

Are there plans to convert this repo into a `PyPI` package? The amount of work needed there could be trivial (as you already seem to have a `setup.py` file and stuff).

That could be incredibly useful.
1. Makes installs super-simple.
2. People (like me!) using this package as a dependency in their code can ship their package easier (just need to add `torchsearchsorted` to `requirements.txt`.

**Comment by aliutkus** [comment]
that's true, I should do that asap

**Comment by krrish94** [comment]
@aliutkus Any ETA on when you expect this?

PS. I'm looking to open up a package to public that uses your (awesome!) library as a dependency, and I'm figuring out what the best way for me would be.

**Comment by aliutkus** [comment]
sorry for the long delays. these times are a bit hectic on my side. 
my main concern is: the behaviour with the 'side' parameter is not good as far as people reported. when just 'left' is required it's ok though.
I would say that if you want things to go fast, you're welcome to do a PR for pypi and upload the package yourself. would that do?
sorry, best regards

**Comment by krrish94** [comment]
Hey, yeah terrible times indeed!

I've been experimenting with `side=right` myself. The fix in my case was to enforce `contiguous()` on input tensors.

For now, I'll rely on a setup script that installs from your repo. I'd rather prefer you upload to pypi at a later time, as that'll help you retain control over the package.

**Comment by aliutkus** [comment]
ok, I will let you know when I made progress on this

interesting, good to know for the side parameter

**Comment by xeTaiz** [comment]
FYI you can also just add 
```git+https://github.com/aliutkus/torchsearchsorted.git@master#egg=torchsearchsorted```
to your requirements.txt in the meanwhile.
Also [PyTorch has an official searchsorted now](https://pytorch.org/docs/stable/generated/torch.searchsorted.html#torch.searchsorted)

**Comment by krrish94** [comment]
@xeTaiz That's the workaround I've been using so far :+1: 
yeah, 1.6 has `searchsorted` implemented now!

Closing

**Comment by aliutkus** [comment]
yes ! at last it's in 1,6 😄 sorry for not updating right now, I'm on vacations and not on my pc
 cheers
