### ISSUE TITLE
How do I install on Win 10?

### ISSUE THREAD

**Issue by HannesStark** [aliutkus/torchsearchsorted#15]
Is it possible to install torchsearchsorted for CUDA on Windows?

I am using VS 2017, Python 3.8.2, PyTorch 1.4, and CUDA 10.1 but running pip install . I always get "5 errors detected in the compilation of searchsorted_cuda_kernel.cpp1.ii

Thanks for any help!

**Comment by aliutkus** [comment]
sorry I got no idea. feel free to update the readme.md and PR with this info when you found out, best

**Comment by aliutkus** [comment]
sorry I got no idea. feel free to update the readme.md and PR with this info when you found out, best
