### ISSUE TITLE
nvcc failed with exit status 1

### ISSUE THREAD

**Issue by grey-area** [aliutkus/torchsearchsorted#16]
I have Ubuntu 18.04, python 3.6.9, and I've tried installing this in a virtual environment with each combination of pytorch 1.3.1 and 1.4.0 and cuda 10.1 and 10.2.

I put symlinks to gcc and g++ 8 in my cuda/bin directory.

When I run pip install . in the root directory I get:

"6 errors detected in the compilation of "/tmp/tmpxft_0000137f_00000000-6_searchsorted_cuda_kernel.cpp1.ii".
    error: command '/usr/bin/nvcc' failed with exit status 1"

(the actual number of errors here was different between cuda 10.1 and cuda 10.2).

Some of the errors during compilation:

"    /home/andrew/.virtualenvs/nerf/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/enum.h(164): error: no instance of function template "c10::visit" matches the argument list
                argument types are: (torch::enumtype::_compute_enum_name, torch::nn::KLDivLossOptions::reduction_t)
              detected during:
                instantiation of "std::string torch::enumtype::get_enum_name(V) [with V=torch::nn::KLDivLossOptions::reduction_t]"
    (176): here
                instantiation of "at::Reduction::Reduction torch::enumtype::reduction_get_enum(V) [with V=torch::nn::KLDivLossOptions::reduction_t]"
    /home/andrew/.virtualenvs/nerf/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/functional/loss.h(49): here
    
    /home/andrew/.virtualenvs/nerf/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/enum.h(164): error: no instance of function template "c10::visit" matches the argument list
                argument types are: (torch::enumtype::_compute_enum_name, torch::nn::MultiLabelSoftMarginLossOptions::reduction_t)
              detected during instantiation of "std::string torch::enumtype::get_enum_name(V) [with V=torch::nn::MultiLabelSoftMarginLossOptions::reduction_t]"
    /home/andrew/.virtualenvs/nerf/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/functional/loss.h(336): here
    
    /home/andrew/.virtualenvs/nerf/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/enum.h(164): error: no instance of function template "c10::visit" matches the argument list
                argument types are: (torch::enumtype::_compute_enum_name, torch::nn::functional::PadFuncOptions::mode_t)
              detected during instantiation of "std::string torch::enumtype::get_enum_name(V) [with V=torch::nn::functional::PadFuncOptions::mode_t]"
    /home/andrew/.virtualenvs/nerf/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/functional/padding.h(40): here
    
    /home/andrew/.virtualenvs/nerf/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/enum.h(164): error: no instance of function template "c10::visit" matches the argument list
                argument types are: (torch::enumtype::_compute_enum_name, torch::nn::functional::InterpolateFuncOptions::mode_t)
              detected during instantiation of "std::string torch::enumtype::get_enum_name(V) [with V=torch::nn::functional::InterpolateFuncOptions::mode_t]"
    /home/andrew/.virtualenvs/nerf/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/functional/upsampling.h(103): here"

Any ideas?

**Comment by sixftninja** [comment]
Were you able to solve this? I'm getting similar errors.

**Comment by aliutkus** [comment]
could you try with latest commit ?

**Comment by aliutkus** [comment]
any news on this ? did you try again with latest commit ?

**Comment by eshafeeqe** [comment]
Hello, 
I am getting similar errors while trying to install. Below the error text.
```
/usr/include/c++/8/bits/basic_string.tcc: In instantiation of ‘static std::basic_string<_CharT, _Traits, _Alloc>::_Rep* std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_S_create(std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’:
  /usr/include/c++/8/bits/basic_string.tcc:578:28:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&, std::forward_iterator_tag) [with _FwdIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
  /usr/include/c++/8/bits/basic_string.h:5052:20:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct_aux(_InIterator, _InIterator, const _Alloc&, std::__false_type) [with _InIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
  /usr/include/c++/8/bits/basic_string.h:5073:24:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&) [with _InIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
  /usr/include/c++/8/bits/basic_string.tcc:656:134:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
  /usr/include/c++/8/bits/basic_string.h:6725:95:   required from here
  /usr/include/c++/8/bits/basic_string.tcc:1067:1: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable() [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’ without object
         __p->_M_set_sharable();
   ^     ~~~~~~~~~
  /usr/include/c++/8/bits/basic_string.tcc: In instantiation of ‘static std::basic_string<_CharT, _Traits, _Alloc>::_Rep* std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_S_create(std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’:
  /usr/include/c++/8/bits/basic_string.tcc:578:28:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&, std::forward_iterator_tag) [with _FwdIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
  /usr/include/c++/8/bits/basic_string.h:5052:20:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct_aux(_InIterator, _InIterator, const _Alloc&, std::__false_type) [with _InIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
  /usr/include/c++/8/bits/basic_string.h:5073:24:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&) [with _InIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
  /usr/include/c++/8/bits/basic_string.tcc:656:134:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
  /usr/include/c++/8/bits/basic_string.h:6730:95:   required from here
  /usr/include/c++/8/bits/basic_string.tcc:1067:1: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable() [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’ without object
  error: command '/usr/local/cuda-10.1/bin/nvcc' failed with exit status 1
```

**Comment by aliutkus** [comment]
what is your gcc/g++ version?

**Comment by eshafeeqe** [comment]
gcc 8, I think  it's  because  of cuda version.

**Comment by eshafeeqe** [comment]
I reinstalled cuda (nvcc) by making gcc-8/g++-8 as default gcc/g++ compilers, then the problem gone.

**Comment by aliutkus** [comment]
great!
