### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by stone100010** [aliutkus/torchsearchsorted#21]
(nerf_pl) hsc@hsc-B150-D3A:~/condaproject/nerf_pl-master/torchsearchsorted$ pip install .
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing /home/hsc/condaproject/nerf_pl-master/torchsearchsorted
Building wheels for collected packages: torchsearchsorted
  Building wheel for torchsearchsorted (setup.py) ... \

**Comment by aliutkus** [comment]
what's the problem ?

**Comment by aliutkus** [comment]
please try again with latest

**Comment by stone100010** [comment]
> 请重新尝试最新



> please try again with latest
I am really sorry, the specific reason is that my video card driver version is too low, I just upgraded the driver, thank you!

**Comment by stone100010** [comment]
> please try again with latest

I am really sorry, the specific reason is that my video card driver version is too low, I just upgraded the driver, thank you!
