### ISSUE TITLE
Error with building wheels

### ISSUE THREAD

**Issue by KovenYu** [aliutkus/torchsearchsorted#22]
Hi Antoine,

When I tried "pip install ." on the root, it spitted out a very long error message, which seems a bit similar to Issue [19](https://github.com/aliutkus/torchsearchsorted/issues/19) (but the solution there does not apply to mine, as I was using the up-to-date master branch). Please see the error message here:
[err.txt](https://github.com/aliutkus/torchsearchsorted/files/4671685/err.txt)

Conditions:
System: Ubuntu 16.04
nvcc: 10.2
gcc/g++: 5.4.0 (as required by [cuda installation guide](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html))
Python packages:
_libgcc_mutex             0.1                        main
absl-py                   0.9.0                    py37_0
blas                      1.0                         mkl
bzip2                     1.0.8                h7b6447c_0
c-ares                    1.15.0            h7b6447c_1001
ca-certificates           2020.1.1                      0
certifi                   2020.4.5.1               py37_0
configargparse            1.1                        py_0
cudatoolkit               10.2.89              hfd86e86_1
cycler                    0.10.0                   py37_0
dbus                      1.13.14              hb2f20db_0
expat                     2.2.6                he6710b0_0
ffmpeg                    4.2.2                h20bf706_0
fontconfig                2.13.0               h9420a91_0
freetype                  2.9.1                h8a8886c_1
glib                      2.63.1               h3eb4bd4_1
gmp                       6.1.2                h6c8ec71_1
gnutls                    3.6.5             h71b1129_1002
grpcio                    1.27.2           py37hf8bcb03_0
gst-plugins-base          1.14.0               hbbd80ab_1
gstreamer                 1.14.0               hb31296c_0
icu                       58.2                 he6710b0_3
imageio                   2.8.0                      py_0
imageio-ffmpeg            0.4.2                      py_0
intel-openmp              2020.1                      217
jpeg                      9b                   h024ee3a_2
kiwisolver                1.2.0            py37hfd86e86_0
lame                      3.100                h7b6447c_0
ld_impl_linux-64          2.33.1               h53a641e_7
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.3                  he6710b0_1
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
libopus                   1.3.1                h7b6447c_0
libpng                    1.6.37               hbc83047_0
libprotobuf               3.11.4               hd408876_0
libstdcxx-ng              9.1.0                hdf63c60_0
libtiff                   4.1.0                h2733197_0
libuuid                   1.0.3                h1bed415_2
libvpx                    1.7.0                h439df22_0
libxcb                    1.13                 h1bed415_1
libxml2                   2.9.9                hea5a465_1
markdown                  3.1.1                    py37_0
matplotlib                3.1.3                    py37_0
matplotlib-base           3.1.3            py37hef1b27d_0
mkl                       2020.1                      217
mkl-service               2.3.0            py37he904b0f_0
mkl_fft                   1.0.15           py37ha843d7b_0
mkl_random                1.1.0            py37hd6b4f25_0
ncurses                   6.2                  he6710b0_1
nettle                    3.4.1                hbb512f6_0
ninja                     1.9.0            py37hfd86e86_0
numpy                     1.18.1           py37h4f9e942_0
numpy-base                1.18.1           py37hde5b4d6_1
olefile                   0.46                     py37_0
opencv-python             4.2.0.34                 pypi_0
openh264                  2.1.0                hd408876_0
openssl                   1.1.1g               h7b6447c_0
pcre                      8.43                 he6710b0_0
pillow                    7.1.2            py37hb39fc2d_0
pip                       20.0.2                   py37_3
protobuf                  3.11.4           py37he6710b0_0
pyparsing                 2.4.7                      py_0
pyqt                      5.9.2            py37h05f1152_2
python                    3.7.7                hcff3b4d_5
python-dateutil           2.8.1                      py_0
pytorch                   1.5.0           py3.7_cuda10.2.89_cudnn7.6.5_0
qt                        5.9.7                h5867ecd_1
readline                  8.0                  h7b6447c_0
setuptools                46.4.0                   py37_0
sip                       4.19.8           py37hf484d3e_0
six                       1.14.0                   py37_0
sqlite                    3.31.1               h62c20be_1
tensorboard               1.14.0           py37hf484d3e_0
tk                        8.6.8                hbc83047_0
torchvision               0.6.0                py37_cu102
tornado                   6.0.4            py37h7b6447c_1
tqdm                      4.46.0                     py_0
werkzeug                  1.0.1                      py_0
wheel                     0.34.2                   py37_0
x264                      1!157.20191217       h7b6447c_0
xz                        5.2.5                h7b6447c_0
zlib                      1.2.11               h7b6447c_3
zstd                      1.3.7                h0b5b093_0

Do you have any idea what is wrong? Any help is deeply appreciated!

Thanks,
Koven

**Comment by aliutkus** [comment]
it looks like I need to update some things again due to changes in pytorch and some deprecations. 
what I'll do is follow the warnings and update the code accordingly. feel free to do it before me if you got time, and PR it.
will keep you posted.
talk soon

**Comment by KovenYu** [comment]
UPDATE: Yes you are correct. When using pytorch 1.4 it works fine.

Thank you! So, to verify that this might be due to the pytorch update, I'll try Pytorch 1.4 and 1.3 to see if everything works fine then.

**Comment by aliutkus** [comment]
ok, good to know, this framework moves so fast =)

**Comment by aliutkus** [comment]
please try again with latest

**Comment by KovenYu** [comment]
The error message is reduced largely but it seems still some problem:

[err2.txt](https://github.com/aliutkus/torchsearchsorted/files/4680087/err2.txt)

**Comment by aliutkus** [comment]
thanks for the reactivity, will continue addressing your warnings 
(it works on my side, even with torch 1.5)

**Comment by KovenYu** [comment]
Thanks! It is not urgent though, because I can use it with an virtual env with torch1.4  :)

**Comment by aliutkus** [comment]
it looks like gcc 5 is no longer supported, see:
https://github.com/NVIDIA/apex/issues/805

if you can, you should use gcc 7, apparently

**Comment by KovenYu** [comment]
yeah, but i dont have root permission so things may get a bit tricky. I will try to install a user-specific gcc 7 in my account later.

**Comment by kwea123** [comment]
I confirm that it still works on pytorch1.5.0 with gcc7.5.0
