### ISSUE TITLE
Will there be tpu support?

### ISSUE THREAD

**Issue by qsobad** [aliutkus/torchsearchsorted#23]
Building wheels failed in colab tpu

`!python --version
!nvcc --version

!sudo apt-get install g++-8 gcc-8
!sudo ln -s /usr/bin/gcc-8 /usr/local/cuda-10.1/bin/gcc
!sudo ln -s /usr/bin/g++-8 /usr/local/cuda-10.1/bin/g++

!pip install torch
%cd /content/
!git clone https://github.com/aliutkus/torchsearchsorted.git
%cd /content/torchsearchsorted
!pip install .`

LOG
`Python 3.6.9
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
Reading package lists... Done
Building dependency tree       
Reading state information... Done
g++-8 is already the newest version (8.4.0-1ubuntu1~18.04).
gcc-8 is already the newest version (8.4.0-1ubuntu1~18.04).
0 upgraded, 0 newly installed, 0 to remove and 31 not upgraded.
ln: failed to create symbolic link '/usr/local/cuda-10.1/bin/gcc': File exists
ln: failed to create symbolic link '/usr/local/cuda-10.1/bin/g++': File exists
Requirement already satisfied: torch in /usr/local/lib/python3.6/dist-packages (1.6.0a0+f5bc91f)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from torch) (1.18.4)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from torch) (0.18.2)
/content/
fatal: destination path 'torchsearchsorted' already exists and is not an empty directory.
/content/torchsearchsorted
Processing /content/torchsearchsorted
Building wheels for collected packages: torchsearchsorted
  Building wheel for torchsearchsorted (setup.py) ... error
  ERROR: Failed building wheel for torchsearchsorted
  Running setup.py clean for torchsearchsorted
Failed to build torchsearchsorted
Installing collected packages: torchsearchsorted`

**Comment by aliutkus** [comment]
which gcc are you actually using ? as you can see, your `ln` didn't succeed

**Comment by qsobad** [comment]
that means already linked:
`lrwxrwxrwx 1 root root 14 Jun  2 03:13 /usr/local/cuda-10.1/bin/gcc -> /usr/bin/gcc-8`

but the error comes from building wheels:
`Building wheels for collected packages: torchsearchsorted
  Building wheel for torchsearchsorted (setup.py) ... error
  ERROR: Failed building wheel for torchsearchsorted
  Running setup.py clean for torchsearchsorted`

because tpu does not have cuda core

**Comment by qsobad** [comment]
at least i hope the cpu version work over pytorch-xla

**Comment by aliutkus** [comment]
since pytorch next stable version will include a `searchsorted` finction, I'll not work too much over it, let's wait and see how it goes
