### ISSUE TITLE
Exception: torchsearchsorted on CUDA device is asked, but it seems that it is not available.

### ISSUE THREAD

**Issue by redyxg** [aliutkus/torchsearchsorted#25]
Everything works fine on CPU. But when I tried to run the **_test.py_** on GPU, exception is raised: 
" **torchsearchsorted on CUDA device is asked, but it seems that it is not available. Please install it**" 
Please see below: 

> 
Looking for 50000x1000 values in 50000x300 entries
NUMPY:  searchsorted in 3538.361ms
CPU:  searchsorted in 2558.010ms
    difference between CPU and NUMPY: 0.000
Traceback (most recent call last):
  File "test.py", line 58, in <module>
    test_GPU = searchsorted(a, v, test_GPU, side)
  File "/home/yin/anaconda3/lib/python3.7/site-packages/torchsearchsorted/searchsorted.py", line 41, in searchsorted
    raise Exception('torchsearchsorted on CUDA device is asked, but it seems '
Exception: torchsearchsorted on CUDA device is asked, but it seems that it is not available. Please install it 
“

**Comment by redyxg** [comment]
Sorry ,similar issue has already been resolved. Hereby I close it

**Comment by ai1361720220000** [comment]
hello, i meet the same issue, could you tell me how you solve it?
