### ISSUE TITLE
license

### ISSUE THREAD

**Issue by soumith** [aliutkus/torchsearchsorted#4]
hi,
i was considering using your code for implementing official pytorch torch.searchsorted, but i can only do that if your repository has a compatible license.

could you please consider adding a license to your codebase? fyi pytorch has a BSD-3 clause license

**Comment by aliutkus** [comment]
sure, will pick the same tomorrow

**Comment by aliutkus** [comment]
done, thanks for your interest !

will btw do the same now for the [1D-interpolation](https://github.com/aliutkus/torchinterp1d) repo if it's useful

best
