### ISSUE TITLE
Exception: torchsearchsorted on CPU is not available. Please install it.

### ISSUE THREAD

**Issue by Veereshdammur** [aliutkus/torchsearchsorted#8]
Hi, 

I am not able to use torchsearchsorted package even after building it successfully. 
Please find the screenshot for the details. what could be the possible reason for this behavior? 

pytorch = 1.3.1 , cuda = 10.2 versions are used to build the package. 

![image](https://user-images.githubusercontent.com/33894917/74242353-09dab400-4cde-11ea-8960-31920a4d4114.png)

**Comment by aliutkus** [comment]
I cannot reproduce the error with pytorch=1.4.0 and cuda=10.1

it looks like pytorch is not yet available for cuda 10.2

this may be the cause of your problem. Can you please try again with cuda 10.1 ?

**Comment by Veereshdammur** [comment]
I am successfully able to use your package with PyTorch = 1.3.1 and Cuda = 10.2 on my local machine (ubuntu 18.04). The above screenshot is taken from the cloud VM machine (Ubuntu 16.04). Not sure why it is not working on the cloud machine as it is also uses PyTorch = 1.3.1 and Cuda = 10.2.

**Comment by aliutkus** [comment]
maybe you could try running `python setup.py install` in the root folder of the directory, that would give more informative output ?

**Comment by Veereshdammur** [comment]
These are the packages installed in the virtual environment
`
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_pytorch_select           0.2                       gpu_0  
blas                      1.0                         mkl  
ca-certificates           2020.1.1                      0  
certifi                   2019.11.28               py36_0  
cffi                      1.14.0           py36h2e261b9_0  
cudatoolkit               10.0.130                      0  
cudnn                     7.6.5                cuda10.0_0  
freetype                  2.9.1                h8a8886c_1  
intel-openmp              2020.0                      166  
jpeg                      9b                   h024ee3a_2  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_0  
mkl                       2020.0                      166  
mkl-service               2.3.0            py36he904b0f_0  
mkl_fft                   1.0.15           py36ha843d7b_0  
mkl_random                1.1.0            py36hd6b4f25_0  
ncurses                   6.1                  he6710b0_1  
ninja                     1.9.0            py36hfd86e86_0  
numpy                     1.18.1                   pypi_0    pypi
numpy-base                1.18.1           py36hde5b4d6_1  
olefile                   0.46                     py36_0  
openssl                   1.1.1d               h7b6447c_4  
pillow                    7.0.0            py36hb39fc2d_0  
pip                       20.0.2                   py36_1  
pycparser                 2.19                     py36_0  
python                    3.6.10               h0371630_0  
pytorch                   1.3.1           cuda100py36h53c1284_0  
readline                  7.0                  h7b6447c_5  
setuptools                45.2.0                   py36_0  
six                       1.14.0                   py36_0  
sqlite                    3.31.1               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
torch                     1.3.0                    pypi_0    pypi
wheel                     0.34.2                   py36_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0  

![image](https://user-images.githubusercontent.com/33894917/74317058-fb8ea580-4d7a-11ea-8286-f59788b9a7ef.png)

`
Please have a look at the output. problem remains same. Please help me to resolve this problem.

**Comment by aliutkus** [comment]
for some reason, you are not building the extension. do you have gcc and nvcc installed ?

**Comment by Veereshdammur** [comment]
@aliutkus, Could you please let us know what is the required compute capability for torchseachsorted package?   My cloud VM has only compute capability of  3.7

**Comment by Veereshdammur** [comment]
![image](https://user-images.githubusercontent.com/33894917/74322057-a0ad7c00-4d83-11ea-88b5-60245891a795.png)

**Comment by Veereshdammur** [comment]
@aliutkus could you please tell me if any other package dependencies (like numpy or Scipy) are there to install your package?

**Comment by Veereshdammur** [comment]
@aliutkus  The issue has been fixed. After deleting the build and dist folders (created from previous builds), I am able to install your package with these dependencies. 
```
Package           Version
----------------- -------
numpy             1.18.1 
pip               18.1   
setuptools        40.6.2 
torch             1.3.1  
torchsearchsorted 1.1    
```

Thanks for your repo :)

**Comment by aliutkus** [comment]
thanks for the feedback
